/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoHandsControl
{
    public class HandsControlRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "nao_hands_control/HandsControl";

        //  0 right, 1 left
        public bool hand;

        public HandsControlRequest()
        {
            this.hand = false;
        }

        public HandsControlRequest(bool hand)
        {
            this.hand = hand;
        }

    }
}
