/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoArmsControl
{
    public class ArmsControl : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "nao_arms_control/ArmsControl";

        public Header header;
        public float[] position_right_arm;
        public float[] position_left_arm;

        public ArmsControl()
        {
            this.header = new Header();
            this.position_right_arm = new float[0];
            this.position_left_arm = new float[0];
        }

        public ArmsControl(Header header, float[] position_right_arm, float[] position_left_arm)
        {
            this.header = header;
            this.position_right_arm = position_right_arm;
            this.position_left_arm = position_left_arm;
        }
    }
}
