/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class BlinkGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/BlinkGoal";

        //  Goal: colours to use for blinking, plus blinking rate mean and sd
        //  Result: true if robot is still blinking (call was pre-empted by another user)
        //  Feedback: last blinked colour
        public ColorRGBA[] colors;
        public ColorRGBA bg_color;
        public Duration blink_duration;
        public float blink_rate_mean;
        public float blink_rate_sd;

        public BlinkGoal()
        {
            this.colors = new ColorRGBA[0];
            this.bg_color = new ColorRGBA();
            this.blink_duration = new Duration();
            this.blink_rate_mean = 0.0f;
            this.blink_rate_sd = 0.0f;
        }

        public BlinkGoal(ColorRGBA[] colors, ColorRGBA bg_color, Duration blink_duration, float blink_rate_mean, float blink_rate_sd)
        {
            this.colors = colors;
            this.bg_color = bg_color;
            this.blink_duration = blink_duration;
            this.blink_rate_mean = blink_rate_mean;
            this.blink_rate_sd = blink_rate_sd;
        }
    }
}
