/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class BlinkResult : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/BlinkResult";

        public bool still_blinking;

        public BlinkResult()
        {
            this.still_blinking = false;
        }

        public BlinkResult(bool still_blinking)
        {
            this.still_blinking = still_blinking;
        }
    }
}
