/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class BlinkFeedback : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/BlinkFeedback";

        public ColorRGBA last_color;

        public BlinkFeedback()
        {
            this.last_color = new ColorRGBA();
        }

        public BlinkFeedback(ColorRGBA last_color)
        {
            this.last_color = last_color;
        }
    }
}
