/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class BodyPoseWithSpeedGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/BodyPoseWithSpeedGoal";

        //  goal: a predefined body pose name :
        //  Crouch, LyingBack, LyingBelly, Sit, SitRelax, Stand, StandInit, StandZero
        public string posture_name;
        public float speed;

        public BodyPoseWithSpeedGoal()
        {
            this.posture_name = "";
            this.speed = 1.0f;
        }

        public BodyPoseWithSpeedGoal(string posture_name, float speed)
        {
            this.posture_name = posture_name;
            this.speed = speed;
        }
    }
}
