/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Nav;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class FollowPathGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/FollowPathGoal";

        //  goal: a path to follow
        public Path path;

        public FollowPathGoal()
        {
            this.path = new Path();
        }

        public FollowPathGoal(Path path)
        {
            this.path = path;
        }
    }
}
