/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class JointAnglesWithSpeedResult : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/JointAnglesWithSpeedResult";

        //  result is the actually reached position
        public JointState goal_position;

        public JointAnglesWithSpeedResult()
        {
            this.goal_position = new JointState();
        }

        public JointAnglesWithSpeedResult(JointState goal_position)
        {
            this.goal_position = goal_position;
        }
    }
}
