/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Trajectory;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class JointTrajectoryGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/JointTrajectoryGoal";

        //  goal: a joint angle trajectory
        public JointTrajectory trajectory;
        //  flag whether motion is absolute (=0, default) or relative (=1)
        public byte relative;

        public JointTrajectoryGoal()
        {
            this.trajectory = new JointTrajectory();
            this.relative = 0;
        }

        public JointTrajectoryGoal(JointTrajectory trajectory, byte relative)
        {
            this.trajectory = trajectory;
            this.relative = relative;
        }
    }
}
