/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class JointAnglesWithSpeedGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/JointAnglesWithSpeedGoal";

        //  goal: a registered body pose name
        public JointAnglesWithSpeed joint_angles;

        public JointAnglesWithSpeedGoal()
        {
            this.joint_angles = new JointAnglesWithSpeed();
        }

        public JointAnglesWithSpeedGoal(JointAnglesWithSpeed joint_angles)
        {
            this.joint_angles = joint_angles;
        }
    }
}
