/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class RunBehaviorGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/RunBehaviorGoal";

        //  Goal [behavior]: name of the behavior to be executed
        //  Result: none, will be set to aborted or preempted
        //  Feedback: none as NaoQI API cannot be queried in this respect
        public string behavior;

        public RunBehaviorGoal()
        {
            this.behavior = "";
        }

        public RunBehaviorGoal(string behavior)
        {
            this.behavior = behavior;
        }
    }
}
