/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class RunBehaviorActionResult : ActionResult<RunBehaviorResult>
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/RunBehaviorActionResult";

        public RunBehaviorActionResult() : base()
        {
            this.result = new RunBehaviorResult();
        }

        public RunBehaviorActionResult(Header header, GoalStatus status, RunBehaviorResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
