/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class SetSpeechVocabularyAction : Action<SetSpeechVocabularyActionGoal, SetSpeechVocabularyActionResult, SetSpeechVocabularyActionFeedback, SetSpeechVocabularyGoal, SetSpeechVocabularyResult, SetSpeechVocabularyFeedback>
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/SetSpeechVocabularyAction";

        public SetSpeechVocabularyAction() : base()
        {
            this.action_goal = new SetSpeechVocabularyActionGoal();
            this.action_result = new SetSpeechVocabularyActionResult();
            this.action_feedback = new SetSpeechVocabularyActionFeedback();
        }

    }
}
