/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class SpeechWithFeedbackActionFeedback : ActionFeedback<SpeechWithFeedbackFeedback>
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/SpeechWithFeedbackActionFeedback";

        public SpeechWithFeedbackActionFeedback() : base()
        {
            this.feedback = new SpeechWithFeedbackFeedback();
        }

        public SpeechWithFeedbackActionFeedback(Header header, GoalStatus status, SpeechWithFeedbackFeedback feedback) : base(header, status)
        {
            this.feedback = feedback;
        }
    }
}
