/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class SpeechWithFeedbackGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/SpeechWithFeedbackGoal";

        //  Purpose : To have feedback on when the speech was started and when 
        //  NAO stopped talking
        //  Goal: The sentence for NAO to say 
        //  Result: NAO has finished speaking
        //  Feedback: When NAO starts speaking
        public string say;

        public SpeechWithFeedbackGoal()
        {
            this.say = "";
        }

        public SpeechWithFeedbackGoal(string say)
        {
            this.say = say;
        }
    }
}
