/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoqiBridge
{
    public class JointAnglesWithSpeed : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "naoqi_bridge_msgs/JointAnglesWithSpeed";

        public Header header;
        //  A list of joint names, corresponding to their names in the Nao docs.
        //  This must be either the same lenght of joint_angles or 1 if it's a
        //  keyword such as 'Body' (for all angles)
        public string[] joint_names;
        public float[] joint_angles;
        // fraction of max joint velocity [0:1]
        public float speed;
        //  Absolute angle(=0, default) or relative change
        public byte relative;

        public JointAnglesWithSpeed()
        {
            this.header = new Header();
            this.joint_names = new string[0];
            this.joint_angles = new float[0];
            this.speed = 0.0f;
            this.relative = 0;
        }

        public JointAnglesWithSpeed(Header header, string[] joint_names, float[] joint_angles, float speed, byte relative)
        {
            this.header = header;
            this.joint_names = joint_names;
            this.joint_angles = joint_angles;
            this.speed = speed;
            this.relative = relative;
        }
    }
}
