/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.NaoHeadControl
{
    public class HeadControl : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "nao_head_control/HeadControl";

        public Header header;
        //  A list of joint names, corresponding to their names in the Nao docs.
        //  This must be either the same lenght of joint_angles or 1 if it's a
        //  keyworord such as 'body' (for all angles)
        public string[] joint_names;
        public float[] joint_angles;
        //  Fraction of max joint velocity [0:1]
        public float speed;

        public HeadControl()
        {
            this.header = new Header();
            this.joint_names = new string[0];
            this.joint_angles = new float[0];
            this.speed = 0.0f;
        }

        public HeadControl(Header header, string[] joint_names, float[] joint_angles, float speed)
        {
            this.header = header;
            this.joint_names = joint_names;
            this.joint_angles = joint_angles;
            this.speed = speed;
        }
    }
}
